repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: ruff
        name: ruff
        entry: uv run ruff check
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: pytest
        name: pytest
        entry: uv run pytest test
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
