# Generated by Django 5.1.5 on 2025-02-05 11:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Player's phone number in E.164 format",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the player has opted in to receive messages",
                    ),
                ),
                (
                    "opted_in_at",
                    models.DateTimeField(
                        blank=True, help_text="When the player last opted in", null=True
                    ),
                ),
                (
                    "opted_out_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the player last opted out",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the player record was created",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        help_text="The word to be described", max_length=100
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="ISO 639-1 language code (e.g., 'es' for Spanish)",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("timeout", "Timeout"),
                        ],
                        default="active",
                        help_text="Current status of the game session",
                        max_length=10,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the game session started",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the game session was completed or timed out",
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        help_text="Score from 0-100 based on AI evaluation",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        help_text="Player participating in this game session",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.player",
                    ),
                ),
            ],
        ),
    ]
