name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv sync
          uv pip install -e ".[dev]"
      
      - name: Run Django migrations
        run: cd src/charades && uv run python manage.py migrate && cd ../..

      - name: Run ruff format check
        run: uv run ruff format --check

      - name: Run ruff linting
        run: uv run ruff check

      - name: Run pyright type checking
        run: uv run pyright

      - name: Run pytest
        run: uv run pytest test
